version: "3.3"

services:

  redis:
    image: redis:6.0.9-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smylet

  app-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/tmp  # for the build cache

volumes:
  db:
    driver: local
  redis-data:
    driver: local

