version: "3.3"
services:
  ## Postgres, redis, minio, etc ...

  
  api:
    image: cosmtrek/air
    working_dir: /project
    ports:
      - 8000:8000
    volumes:
      - ./:/project/ 
    # links: 
    # - postgres
    container_name: api

